baseURL = "https://secondhandbooks.onrender.com/"
languageCode = "en-us"
title = "Second Hand Books"
theme = "aether"

[params]
    brand = "2HB"
    description = "The biggest collection of used books in Sri Lanka"

[outputs]
    home = ["HTML", "RSS", "JSON"]